// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ProcessImagesBatch(arg1:model.BatchRequest):Promise<model.BatchResult>;

export function ScanDirectory(arg1:string,arg2:boolean):Promise<Array<string>>;
