// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessImagesBatch(arg1) {
  return window['go']['main']['App']['ProcessImagesBatch'](arg1);
}

export function ScanDirectory(arg1, arg2) {
  return window['go']['main']['App']['ScanDirectory'](arg1, arg2);
}
