// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBatch() {
  return window['go']['main']['App']['CancelBatch']();
}

export function GetAiOutputDir() {
  return window['go']['main']['App']['GetAiOutputDir']();
}

export function GetApiKey() {
  return window['go']['main']['App']['GetApiKey']();
}

export function OpenOutputDir(arg1) {
  return window['go']['main']['App']['OpenOutputDir'](arg1);
}

export function PreviewWatermark(arg1) {
  return window['go']['main']['App']['PreviewWatermark'](arg1);
}

export function ProcessImagesBatch(arg1) {
  return window['go']['main']['App']['ProcessImagesBatch'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['main']['App']['ReadImageAsBase64'](arg1);
}

export function ReadImageThumbnail(arg1, arg2) {
  return window['go']['main']['App']['ReadImageThumbnail'](arg1, arg2);
}

export function RunAIImageBatch(arg1) {
  return window['go']['main']['App']['RunAIImageBatch'](arg1);
}

export function SaveAiOutputDir(arg1) {
  return window['go']['main']['App']['SaveAiOutputDir'](arg1);
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function ScanDirectory(arg1, arg2) {
  return window['go']['main']['App']['ScanDirectory'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function SliceImages(arg1) {
  return window['go']['main']['App']['SliceImages'](arg1);
}

export function WatermarkImages(arg1) {
  return window['go']['main']['App']['WatermarkImages'](arg1);
}
