// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {shell} from '../models';
import {context} from '../models';

export function CancelBatch():Promise<void>;

export function FetchProviderModels(arg1:string):Promise<Array<model.ModelInfo>>;

export function GetActiveProvider():Promise<string>;

export function GetAiOutputDir():Promise<string>;

export function GetImageInfo(arg1:string):Promise<Record<string, any>>;

export function GetPendingIntent():Promise<shell.LaunchIntent>;

export function GetProviderConfig(arg1:string):Promise<model.ProviderConfigResponse>;

export function GetProviderModels(arg1:string):Promise<Array<model.ModelInfo>>;

export function HandleLaunchIntent(arg1:shell.LaunchIntent):Promise<void>;

export function InstallContextMenu():Promise<void>;

export function IsContextMenuInstalled():Promise<boolean>;

export function IsDir(arg1:string):Promise<boolean>;

export function OpenOutputDir(arg1:string):Promise<void>;

export function PreviewWatermark(arg1:model.WatermarkPreviewRequest):Promise<string>;

export function ProcessImagesBatch(arg1:model.BatchRequest):Promise<model.BatchResult>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReadImageThumbnail(arg1:string,arg2:number):Promise<string>;

export function RedrawBuyerShowImage(arg1:model.BuyerShowRedrawRequest):Promise<model.BuyerShowSlotResult>;

export function RewriteBuyerShowReview(arg1:model.BuyerShowReviewRewriteRequest):Promise<model.BuyerShowReviewRewriteResult>;

export function RunAIImageBatch(arg1:model.AIBatchRequest):Promise<model.BatchResult>;

export function RunBuyerShowBatch(arg1:model.BuyerShowBatchRequest):Promise<model.BuyerShowBatchResult>;

export function SaveAiOutputDir(arg1:string):Promise<void>;

export function SaveApiKey(arg1:string):Promise<void>;

export function SaveFilesToDir(arg1:Array<string>,arg2:string,arg3:number):Promise<number>;

export function SaveProviderConfig(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SaveProviderReviewConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanBuyerShowImport(arg1:model.BuyerShowScanRequest):Promise<model.BuyerShowScanResult>;

export function ScanDirectory(arg1:string,arg2:boolean):Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectOutputDir():Promise<string>;

export function SetActiveProvider(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPendingIntent(arg1:shell.LaunchIntent):Promise<void>;

export function SliceImages(arg1:model.SliceRequest):Promise<model.BatchResult>;

export function UninstallContextMenu():Promise<void>;

export function WatermarkImages(arg1:model.WatermarkRequest):Promise<model.BatchResult>;
