// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessImagesBatch(arg1) {
  return window['go']['main']['App']['ProcessImagesBatch'](arg1);
}

export function ScanDirectory(arg1, arg2) {
  return window['go']['main']['App']['ScanDirectory'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function SliceImages(arg1) {
  return window['go']['main']['App']['SliceImages'](arg1);
}

export function WatermarkImages(arg1) {
  return window['go']['main']['App']['WatermarkImages'](arg1);
}
