// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function CancelBatch():Promise<void>;

export function GetAiOutputDir():Promise<string>;

export function GetApiKey():Promise<string>;

export function GetImageInfo(arg1:string):Promise<Record<string, any>>;

export function OpenOutputDir(arg1:string):Promise<void>;

export function PreviewWatermark(arg1:model.WatermarkPreviewRequest):Promise<string>;

export function ProcessImagesBatch(arg1:model.BatchRequest):Promise<model.BatchResult>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReadImageThumbnail(arg1:string,arg2:number):Promise<string>;

export function RunAIImageBatch(arg1:model.AIBatchRequest):Promise<model.BatchResult>;

export function SaveAiOutputDir(arg1:string):Promise<void>;

export function SaveApiKey(arg1:string):Promise<void>;

export function ScanDirectory(arg1:string,arg2:boolean):Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectOutputDir():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SliceImages(arg1:model.SliceRequest):Promise<model.BatchResult>;

export function WatermarkImages(arg1:model.WatermarkRequest):Promise<model.BatchResult>;
